version: '3'

services:
  api:
    build: .
    volumes:
      - kvrest_data:/app/data
    env_file:
      - .env
    restart: always

  my-backup-unit:
    image: peterrus/s3-cron-backup
    env_file:
      - .backuper.env
    environment:
      - CRON_SCHEDULE=*/1 * * * *
      - BACKUP_NAME=kvrestbackup
    volumes:
      - kvrest_data:/data:ro #use ro to make sure the volume gets mounted read-only
    restart: always

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - ./site/index.html:/var/www/kvrest/index.html
      - caddy_config:/config
    restart: always

volumes:
  kvrest_data:
  caddy_data:
  caddy_config: